# Generated by Django 6.0.4 on 2026-05-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
        migrations.RemoveField(
            model_name='files',
            name='file_path',
        ),
        migrations.AddField(
            model_name='files',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(choices=[('upload', 'Upload'), ('get', 'Get'), ('delete', 'Delete')], default='upload', max_length=10),
        ),
    ]
