# Generated by Django 6.0.4 on 2026-05-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_files_options_alter_logs_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
